### PR TITLE
Close repoclosure issue on success

### PR DESCRIPTION
**Pull request by janosdebugs**
## Changes introduced with this PR

This PR adds a CI job to close the `repoclosure-failed` issue when it succeeds.

## Are you the owner of the code you are sending in, or do you have permission of the owner?

[y/n] Yes

### CODE REVIEW

**Comment by janosdebugs** [comment]
@sandrobonazzola CI seems to be broken?

**Review by sandrobonazzola — APPROVED** [review]
LGTM

**Comment by sandrobonazzola** [comment]
Looks like the failing command is `yum module enable -y javapackages-tools:201801`.
Checking what changed in CentOS Stream since this morning...

**Comment by sandrobonazzola** [comment]
Nope, it's CI bug:
```
echo ${{ github.base_ref }}
echo ${{ github.ref }}
```

Is printing:

```
''
'refs/heads/close-repoclosure-issue-on-success'
```

Looks like the base_ref is not set for this PR.

**Comment by sandrobonazzola** [comment]
closing, merged via pr #37

**Pull request closed without merging**
