### PR TITLE
el8-stream: drop advanced virtualization

### PR DESCRIPTION
**Pull request by sandrobonazzola**
Advanced virtualization is now included in AppStream: removing from needed repos for CentOS Stream.

Signed-off-by: Sandro Bonazzola <sbonazzo@redhat.com>

### CODE REVIEW

**Comment by didib** [comment]
Perhaps wait with this one a bit, until the issues with qemu-kvm-6.1.0 are sorted out. This patch will make it slightly harder to downgrade to 6.0.0.

**Comment by sandrobonazzola** [comment]
Moving to draft, waiting to get qemu-kvm fix in AppStream

**Comment by didib** [comment]
Perhaps wait for qemu 6.2

**Comment by sandrobonazzola** [comment]
qemu-kvm 6.2 landed on mirrors

**Review by lveyde — APPROVED** [review]

**Pull request merged**
